### ISSUE TITLE
Support ESLint v8

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/eslint-config#27]
DoD:

- [x] Remove `eslint` from `dependencies`
- [x] Update `eslint` in `peerDependencies` for v8
- [x] Bump default ecmaVersion to ES2020
- [x] Check plugins compatibility and update it
  - [x] `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` https://github.com/typescript-eslint/typescript-eslint/issues/3738
  - [x] `eslint-config-prettier` https://github.com/prettier/eslint-config-prettier/issues/200
  - [x] `eslint-plugin-prettier` https://github.com/prettier/eslint-plugin-prettier/issues/427
  - [ ] `eslint-import-resolver-typescript` ???
  - [ ] `eslint-plugin-dirs` ???
  - [x] `eslint-plugin-flowtype` https://github.com/gajus/eslint-plugin-flowtype/issues/495
  - [ ] `eslint-plugin-header` ???
  - [x] `eslint-plugin-import` https://github.com/import-js/eslint-plugin-import/issues/2211
  - [x] `eslint-plugin-jest` https://github.com/jest-community/eslint-plugin-jest/issues/881
  - [x] `eslint-plugin-jest-dom` https://github.com/testing-library/eslint-plugin-jest-dom/issues/190
  - [x] `eslint-plugin-jsx-a11y` https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/809
  - [ ] ~~`eslint-plugin-node` https://github.com/mysticatea/eslint-plugin-node/issues/294~~
    - [ ] Use `eslint-plugin-n` instead `eslint-plugin-node`
  - [x] `eslint-plugin-react` https://github.com/yannickcr/eslint-plugin-react/issues/3055
  - [x] `eslint-plugin-react-hooks` https://github.com/facebook/react/issues/22246
  - [x] `eslint-plugin-simple-import-sort` https://github.com/lydell/eslint-plugin-simple-import-sort/issues/85
  - [x] `eslint-plugin-sonarjs` https://github.com/SonarSource/eslint-plugin-sonarjs/issues/286
  - [x] `eslint-plugin-testing-library` https://github.com/testing-library/eslint-plugin-testing-library/issues/462
  - [x] `eslint-plugin-unicorn` https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1486

**Comment by KillWolfVlad** [comment]
See PR https://github.com/Byndyusoft/eslint-config/pull/30
